const menu = [
  {
    id: 1,
    title: "Panquecas",
    category: "café da manhã",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `hdednweiu dwneiduendu enuidendiedeiund eudneudniud2ni `,
  },
  {
    id: 2,
    title: "Jantar duplo",
    category: "almoço",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `nani nainnaninniia insininisniani ininwuwunwunw nisnuwnuwnuuw niwniwunwuuwuw `,
  },
  {
    id: 3,
    title: "Milkshake Godzilla",
    category: "milkshakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `jhsjsjhaahs  ajjsnsjjna  sjnnajajaj jajnajsjsj jansjsnjsj`,
  },
  {
    id: 4,
    title: "Delicias do interior",
    category: "café da manhã",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "Ovos mexidos",
    category: "almoço",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "Sonho de óreo",
    category: "milkshakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "  bacons fritos",
    category: "café da manhã",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "classico",
    category: "almoço",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "Milkshake da Quarentena",
    category: "milkshakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
